name: RunPod LangFlow
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/runpod-langflow .
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/runpod-langflow